### ISSUE TITLE
update git worklow

### ISSUE THREAD

**Issue by benjy8001** [benjy8001/php-fpm-opencv#4]
```
   name: Docker Image CI

   on:
     push:
       branches: [ master ]
     pull_request:
       branches: [ master ]

   jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: make build
      - name: Push the Docker image
        run: make push_image
```
